### ISSUE TITLE
请问下大佬 这东西会不会黑号啊

### ISSUE THREAD

**Issue by wj2008** [6dylan6/auto_comment#11]
功能太牛逼了 我都不太敢用 哈哈

**Comment by wj2008** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/6dylan6_auto_comment_main/jd_comment.py", line 679, in <module>
    main(opts)
  File "/ql/data/scripts/6dylan6_auto_comment_main/jd_comment.py", line 534, in main
    N = sunbw(N, opts)
        ^^^^^^^^^^^^^^
  File "/ql/data/scripts/6dylan6_auto_comment_main/jd_comment.py", line 284, in sunbw
    imgdata = req1.json()
              ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)



imgdata = req1.json() 
这里报错了 要不要修一下？
